services:
  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "4321:4321"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/astro_db
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=astro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: